spring:
  application:
    name: hospital_clinical
  profiles:
    default: local
  jpa:
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:hospital_clinical;MODE=Oracle;DATABASE_TO_UPPER=true;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS HOSPITAL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: HOSPITAL

server:
  port: ${SERVER_PORT:8090}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: HOSPITAL

server:
  port: ${SERVER_PORT:8090}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: HOSPITAL

server:
  port: ${SERVER_PORT:8080}
